import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireModerator } from "@/lib/admin";

export async function GET() {
  const auth = await requireModerator();
  if (auth.error) return auth.error;

  const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const [
    totalUsers,
    pendingApproval,
    activeUsers,
    suspendedOrBanned,
    adminCount,
    moderatorCount,
    pendingReports,
    totalReports,
    unusedInvites,
    usedInvites,
    newUsersThisWeek,
    newUsersToday,
    totalPosts,
    postsToday,
    totalComments,
    totalMessages,
    totalConversations,
    totalNotifications,
    totalLikes,
    recentPendingUsers,
    recentUsers,
    recentReports,
    recentPosts,
    recentActivity,
  ] = await Promise.all([
    prisma.user.count(),
    prisma.user.count({ where: { status: "PENDING_APPROVAL" } }),
    prisma.user.count({ where: { status: "ACTIVE" } }),
    prisma.user.count({ where: { status: { in: ["SUSPENDED", "BANNED"] } } }),
    prisma.user.count({ where: { role: "ADMIN" } }),
    prisma.user.count({ where: { role: "MODERATOR" } }),
    prisma.report.count({ where: { status: { in: ["PENDING", "UNDER_REVIEW"] } } }),
    prisma.report.count(),
    prisma.invite.count({ where: { status: "UNUSED" } }),
    prisma.invite.count({ where: { status: "USED" } }),
    prisma.user.count({ where: { createdAt: { gte: weekAgo } } }),
    prisma.user.count({ where: { createdAt: { gte: dayAgo } } }),
    prisma.post.count({ where: { deletedAt: null } }),
    prisma.post.count({ where: { deletedAt: null, createdAt: { gte: dayAgo } } }),
    prisma.comment.count(),
    prisma.message.count(),
    prisma.conversation.count(),
    prisma.notification.count(),
    prisma.like.count(),
    prisma.user.findMany({
      where: { status: "PENDING_APPROVAL" },
      orderBy: { createdAt: "desc" },
      take: 5,
      select: {
        id: true,
        username: true,
        email: true,
        createdAt: true,
        profile: { select: { displayName: true } },
      },
    }),
    prisma.user.findMany({
      orderBy: { createdAt: "desc" },
      take: 8,
      select: {
        id: true,
        username: true,
        email: true,
        role: true,
        status: true,
        createdAt: true,
        profile: { select: { displayName: true } },
      },
    }),
    prisma.report.findMany({
      where: { status: { in: ["PENDING", "UNDER_REVIEW"] } },
      orderBy: { createdAt: "desc" },
      take: 6,
      include: { reporter: { select: { username: true } } },
    }),
    prisma.post.findMany({
      where: { deletedAt: null },
      orderBy: { createdAt: "desc" },
      take: 8,
      select: {
        id: true,
        content: true,
        visibility: true,
        createdAt: true,
        author: { select: { username: true, profile: { select: { displayName: true } } } },
        _count: { select: { comments: true, likes: true } },
      },
    }),
    prisma.auditLog.findMany({
      orderBy: { createdAt: "desc" },
      take: 12,
      include: { user: { select: { username: true } } },
    }),
  ]);

  return NextResponse.json({
    totals: {
      users: totalUsers,
      pendingApproval,
      activeUsers,
      suspendedOrBanned,
      admins: adminCount,
      moderators: moderatorCount,
      pendingReports,
      totalReports,
      unusedInvites,
      usedInvites,
      newUsersThisWeek,
      newUsersToday,
      posts: totalPosts,
      postsToday,
      comments: totalComments,
      messages: totalMessages,
      conversations: totalConversations,
      notifications: totalNotifications,
      likes: totalLikes,
    },
    recentPendingUsers: recentPendingUsers.map((u) => ({
      id: u.id,
      username: u.username,
      email: u.email,
      displayName: u.profile?.displayName,
      createdAt: u.createdAt.toISOString(),
    })),
    recentUsers: recentUsers.map((u) => ({
      id: u.id,
      username: u.username,
      email: u.email,
      role: u.role,
      status: u.status,
      displayName: u.profile?.displayName,
      createdAt: u.createdAt.toISOString(),
    })),
    recentReports: recentReports.map((r) => ({
      id: r.id,
      targetType: r.targetType,
      reason: r.reason,
      status: r.status,
      reporterUsername: r.reporter.username,
      createdAt: r.createdAt.toISOString(),
    })),
    recentPosts: recentPosts.map((p) => ({
      id: p.id,
      content: p.content,
      visibility: p.visibility,
      authorUsername: p.author.username,
      authorDisplayName: p.author.profile?.displayName,
      commentCount: p._count.comments,
      likeCount: p._count.likes,
      createdAt: p.createdAt.toISOString(),
    })),
    recentActivity: recentActivity.map((a) => ({
      id: a.id,
      action: a.action,
      username: a.user?.username ?? null,
      ipAddress: a.ipAddress,
      createdAt: a.createdAt.toISOString(),
    })),
  });
}
